;;; heroiclands-project-test.el --- Repository discovery checks -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'cl-lib)
(require 'heroiclands)

(define-derived-mode markdown-mode text-mode "Markdown")

(ert-deftest heroiclands-mode-recognizes-note-frontmatter-at-any-path ()
  (dolist (case '(("---\ntype: lore\nshortcode: moved\n---\n" . t)
                  ("---\nshortcode: moved\ntype: lore\n---\n" . t)
                  ("---\ntype: lore\n---\nshortcode: moved\n" . nil)
                  ("---\nshortcode: moved\n---\ntype: lore\n" . nil)
                  ("---\ntype: lore\nshortcode: \n---\n" . nil)
                  ("---\ntype: lore\nshortcode: \"\"\n---\n" . nil)
                  ("---\n  type: lore\nshortcode: moved\n---\n" . nil)
                  ("# README\n\ntype: lore\nshortcode: moved\n" . nil)))
    (with-temp-buffer
      (markdown-mode)
      (setq buffer-file-name "/tmp/moved/Guide.md")
      (insert (car case))
      (goto-char (point-max))
      (should (eq (and (heroiclands--note-p) t) (cdr case)))
      (heroiclands-mode-maybe-enable)
      (should (eq (and heroiclands-mode t) (cdr case))))))

(ert-deftest heroiclands-note-recognition-preserves-buffer-position ()
  (with-temp-buffer
    (markdown-mode)
    (insert "---\ntype: lore\nshortcode: moved\n---\nBody\n")
    (goto-char (point-max))
    (set-mark (1- (point)))
    (narrow-to-region (line-beginning-position) (point-max))
    (let ((position (point))
          (marked (mark))
          (start (point-min))
          (end (point-max)))
      (should (heroiclands--note-p))
      (should (= (point) position))
      (should (= (mark) marked))
      (should (= (point-min) start))
      (should (= (point-max) end)))))

(ert-deftest heroiclands-switch-project-includes-a-repository-root ()
  (let* ((directory (make-temp-file "heroiclands-projects-" t))
         (direct (expand-file-name "direct" directory))
         (group (expand-file-name "group" directory))
         (child (expand-file-name "child" group))
         (heroiclands-project-roots (list direct group))
         selected)
    (unwind-protect
        (progn
          (dolist (repo (list direct child))
            (make-directory repo t)
            (with-temp-file (expand-file-name ".git" repo)
              (insert "gitdir: elsewhere\n")))
          (should (equal (heroiclands--git-repos)
                         (list (file-name-as-directory direct)
                               (file-name-as-directory child))))
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_prompt candidates &rest _args)
                       (should (equal candidates '("direct" "child")))
                       "direct"))
                    ((symbol-function 'project-switch-project)
                     (lambda (directory) (setq selected directory))))
            (heroiclands-switch-project))
          (should (equal selected (file-name-as-directory direct))))
      (delete-directory directory t))))

;;; heroiclands-project-test.el ends here
