;;; heroiclands-eglot-test.el --- Eglot integration checks -*- lexical-binding: t; -*-
;; SPDX-License-Identifier: GPL-3.0-or-later

(require 'ert)
(require 'cl-lib)
(require 'heroiclands-eglot)

(define-derived-mode markdown-mode text-mode "Markdown")

(ert-deftest heroiclands-eglot-forwards-field-qualified-xref-queries ()
  (with-temp-buffer
    (let (queries)
      (cl-letf (((symbol-function 'eglot-server-capable)
                 (lambda (_capability) t))
                ((symbol-function 'eglot--current-server-or-lose)
                 (lambda () 'server))
                ((symbol-function 'eglot--request)
                 (lambda (_server _method params)
                   (push (plist-get params :query) queries)
                   nil)))
        (dolist (query '("camel" "tag:myth" "name:camel"
                         "shortcode:bctrncml" "type:being"
                         "all:name:camel" "package:thalorna name:camel"
                         "package:unconfigured name:camel"))
          (should-not (xref-backend-apropos 'eglot query)))
        (should (equal (nreverse queries)
                       '("camel" "tag:myth" "name:camel"
                         "shortcode:bctrncml" "type:being"
                         "all:name:camel" "package:thalorna name:camel"
                         "package:unconfigured name:camel")))))))

(ert-deftest heroiclands-eglot-enables-flymake-with-server-diagnostics ()
  (with-temp-buffer
    (let (enabled)
      (cl-letf (((symbol-function 'eglot-managed-p) (lambda () t))
                ((symbol-function 'heroiclands-eglot--content-buffer-p)
                 (lambda () t))
                ((symbol-function 'flymake-mode)
                 (lambda (value) (setq enabled value))))
        (heroiclands-eglot--manage-capf)
        (should (equal enabled 1))
        (should (memq #'heroiclands-eglot-capf completion-at-point-functions))
        (heroiclands-eglot--teardown-capf)
        (should-not (memq #'heroiclands-eglot-capf completion-at-point-functions))
        (should (equal enabled 1))))))

(ert-deftest heroiclands-eglot-starts-only-in-recognized-notes ()
  (let* ((root (make-temp-file "heroiclands-eglot-" t))
         (content (expand-file-name "assets/content" root))
         (inside (expand-file-name "README.md" content))
         (outside (expand-file-name "Guide.md" root))
         (started 0))
    (unwind-protect
        (progn
          (make-directory content t)
          (dolist (file (list inside outside))
            (with-temp-buffer
              (markdown-mode)
              (insert (if (equal file outside)
                          "---\ntype: lore\nshortcode: moved\n---\n"
                        "# README\n"))
              (setq buffer-file-name file
                    default-directory root
                    heroiclands-mode t)
              (cl-letf (((symbol-function 'heroiclands--project-root)
                         (lambda () root))
                        ((symbol-function 'heroiclands-project-p)
                         (lambda (_directory) t))
                        ((symbol-function 'eglot-ensure)
                         (lambda () (cl-incf started))))
                (heroiclands-eglot--maybe-start)
                (if (equal file outside)
                    (progn
                      (should (= started 1))
                      (should (local-variable-p 'eglot-server-programs))
                      (should (eq (cdar eglot-server-programs)
                                  'heroiclands-eglot--contact)))
                  (should (= started 0))
                  (should-not (local-variable-p 'eglot-server-programs)))))))
      (delete-directory root t))))

(ert-deftest heroiclands-eglot-command-uses-pinned-server ()
  (let* ((root (make-temp-file "heroiclands-eglot-" t))
         (content (expand-file-name "assets/content" root))
         (binary (expand-file-name
                  "editor/node_modules/.bin/heroiclands-content-language-server" root))
         (heroiclands-server-directory (expand-file-name "editor" root))
         (heroiclands-index-projects nil))
    (unwind-protect
        (progn
          (make-directory content t)
          (make-directory (file-name-directory binary) t)
          (with-temp-file binary (insert "#!/bin/sh\n"))
          (set-file-modes binary #o755)
          (with-temp-buffer
            (markdown-mode)
            (insert "---\ntype: lore\nshortcode: guide\n---\n")
            (setq buffer-file-name (expand-file-name "Guide.md" content)
                  default-directory root
                  heroiclands-mode t)
            (cl-letf (((symbol-function 'heroiclands--project-root)
                       (lambda () root))
                      ((symbol-function 'heroiclands-project-p)
                       (lambda (_directory) t)))
              (let ((contact (heroiclands-eglot--contact)))
                (should (equal (car contact) binary))
                (should (equal (funcall (plist-get (cdr contact)
                                                  :initializationOptions)
                                        nil)
                               '(:foreignRoots [])))))))
      (delete-directory root t))))

(ert-deftest heroiclands-eglot-selects-foreign-roots-without-an-index ()
  (let* ((directory (make-temp-file "heroiclands-eglot-projects-" t))
         (root (expand-file-name "local" directory))
         (foreign (expand-file-name "renamed-project" directory))
         (other (expand-file-name "other-project" directory))
         (content (expand-file-name "assets/content" root))
         (heroiclands-eglot-server-command '("server")))
    (unwind-protect
        (progn
          (mapc (lambda (path) (make-directory path t))
                (list content foreign other))
          (with-temp-buffer
            (markdown-mode)
            (insert "---\ntype: lore\nshortcode: guide\n---\n")
            (setq buffer-file-name (expand-file-name "Guide.md" content)
                  default-directory root
                  heroiclands-mode t)
            (cl-letf (((symbol-function 'heroiclands--project-root)
                       (lambda () root))
                      ((symbol-function 'heroiclands-project-p)
                       (lambda (_directory) t))
                      ((symbol-function 'heroiclands-projects)
                       (lambda (&optional _refresh) (list root foreign other)))
                      ((symbol-function 'heroiclands-project-package)
                       (lambda (project)
                         (cond ((equal project foreign) "thalorna")
                               ((equal project other) "kethira")))))
              (dolist (case `((all ,foreign ,other)
                              (("thalorna") ,foreign)
                              ((,foreign) ,foreign)
                              (nil)))
                (let* ((heroiclands-index-projects (car case))
                       (contact (heroiclands-eglot--contact))
                       (options (funcall (plist-get (cdr contact)
                                                    :initializationOptions)
                                         nil)))
                  (should (equal (car contact) "server"))
                  (should (equal (append (plist-get options :foreignRoots) nil)
                                 (mapcar #'file-truename (cdr case)))))))))
      (delete-directory directory t))))

(ert-deftest heroiclands-eglot-capf-retains-server-candidates-and-selection ()
  (with-temp-buffer
    (insert "[[camel")
    (goto-char (point-max))
    (setq heroiclands-goto--entry (copy-marker (+ (point-min) 2)))
    (let* ((item '(:label "Xerathian Bactrian Camel — thalorna-sohl-being-bctrncml"
                   :filterText "camel"
                   :textEdit (:newText "sohl-being-bctrncml")
                   :data (:address "thalorna-sohl-being-bctrncml"
                          :display "Xerathian Bactrian Camel")))
           (candidate (propertize "Xerathian Bactrian Camel" 'eglot--lsp-item item))
           (table (list candidate))
           (exited nil))
      (cl-letf (((symbol-function 'heroiclands-eglot--content-buffer-p)
                 (lambda () t))
                ((symbol-function 'eglot-managed-p) (lambda () t))
                ((symbol-function 'eglot-completion-at-point)
                 (lambda ()
                   (list (+ (point-min) 2) (point) table
                         :exit-function
                         (lambda (_candidate _status)
                           (delete-region (+ (point-min) 2) (point))
                           (insert "sohl-being-bctrncml")
                           (setq exited t))))))
        (let ((capf (heroiclands-eglot-capf)))
          (should (eq (nth 2 capf) table))
          (should (eq (plist-get (nthcdr 3 capf) :exclusive) 'no))
          (funcall (plist-get (nthcdr 3 capf) :exit-function) candidate 'finished)
          (should exited)
          (should (equal (plist-get heroiclands-goto--selected :address)
                         "sohl-being-bctrncml"))
          (should (equal (plist-get heroiclands-goto--selected :canonical)
                         "thalorna-sohl-being-bctrncml"))
          (insert "]]")
          (let ((last-command-event ?\]))
            (heroiclands-goto--close-link))
          (should (equal (buffer-string)
                         "[[sohl-being-bctrncml|Xerathian Bactrian Camel]]")))))))

(ert-deftest heroiclands-eglot-capf-finishes-a-paired-wikilink ()
  (dolist (point-after-pair '(nil t))
    (with-temp-buffer
      (insert "[[bao]]")
      (backward-char 2)
      (setq heroiclands-goto--entry (copy-marker (+ (point-min) 2)))
      (let* ((address "skill-baobabbombwesprt")
             (item `(:label "Baobab Spirit Power"
                      :textEdit (:newText ,address)
                      :data (:address "thalorna-sohl-skill-baobabbombwesprt"
                             :display "Baobab Spirit Power")))
             (candidate (propertize "Baobab Spirit Power" 'eglot--lsp-item item)))
        (cl-letf (((symbol-function 'heroiclands-eglot--content-buffer-p)
                   (lambda () t))
                  ((symbol-function 'eglot-managed-p) (lambda () t))
                  ((symbol-function 'eglot-completion-at-point)
                   (lambda ()
                     (list (+ (point-min) 2) (point) (list candidate)
                           :exit-function
                           (lambda (_candidate _status)
                             (delete-region (+ (point-min) 2) (point))
                             (insert address)
                             (when point-after-pair (forward-char 2)))))))
          (let ((capf (heroiclands-eglot-capf)))
            (funcall (plist-get (nthcdr 3 capf) :exit-function)
                     candidate 'finished)
            (should (equal (buffer-string)
                           "[[skill-baobabbombwesprt|Baobab Spirit Power]]"))
            (should-not heroiclands-goto--entry)
            (should-not heroiclands-goto--selected)))))))

(ert-deftest heroiclands-eglot-capf-keeps-substring-results ()
  (with-temp-buffer
    (insert "[[camel")
    (goto-char (point-max))
    (setq heroiclands-goto--entry (copy-marker (+ (point-min) 2)))
    (let ((items (vconcat
                  (mapcar (lambda (name)
                            (list :label name :filterText "camel"
                                  :textEdit (list :newText "being-example")))
                          '("Bactrian Camel" "Xerathian Bactrian Camel"
                            "Bicamelan Triceritops")))))
      (cl-letf (((symbol-function 'heroiclands-eglot--content-buffer-p)
                 (lambda () t))
                ((symbol-function 'eglot-managed-p) (lambda () t))
                ((symbol-function 'eglot-server-capable)
                 (lambda (&rest _args) '(:triggerCharacters ["["])))
                ((symbol-function 'eglot--server-capable)
                 (lambda (&rest _args) '(:triggerCharacters ["["])))
                ((symbol-function 'eglot--current-server-or-lose)
                 (lambda () 'server))
                ((symbol-function 'eglot--request)
                 (lambda (&rest _args) items))
                ((symbol-function 'jsonrpc-request)
                 (lambda (&rest _args) items))
                ((symbol-function 'eglot--CompletionParams)
                 (lambda () nil)))
        (let* ((capf (heroiclands-eglot-capf))
               (matches (funcall (nth 2 capf) "camel" nil t)))
          (should (= (length matches) 3))
          (should (seq-some (lambda (item)
                              (string-match-p "Bicamelan" item))
                            matches)))))))

(ert-deftest heroiclands-eglot-capf-offers-server-anchors ()
  (with-temp-buffer
    (insert "[[being-orca#dos")
    (goto-char (point-max))
    (setq heroiclands-goto--entry (copy-marker (+ (point-min) 2)))
    (let ((items [(:label "dossier" :filterText "dos"
                   :textEdit (:newText "dossier"))]))
      (cl-letf (((symbol-function 'heroiclands-eglot--content-buffer-p)
                 (lambda () t))
                ((symbol-function 'eglot-managed-p) (lambda () t))
                ((symbol-function 'eglot-server-capable)
                 (lambda (&rest _args) '(:triggerCharacters ["#"])))
                ((symbol-function 'eglot--server-capable)
                 (lambda (&rest _args) '(:triggerCharacters ["#"])))
                ((symbol-function 'eglot--current-server-or-lose)
                 (lambda () 'server))
                ((symbol-function 'eglot--request)
                 (lambda (&rest _args) items))
                ((symbol-function 'jsonrpc-request)
                 (lambda (&rest _args) items))
                ((symbol-function 'eglot--CompletionParams)
                 (lambda () nil)))
        (let* ((capf (heroiclands-eglot-capf))
               (matches (funcall (nth 2 capf) "dos" nil t)))
          (should (equal (mapcar #'substring-no-properties matches)
                         '("dossier"))))))))

(ert-deftest heroiclands-eglot-capf-coexists-with-other-completion-and-mode-teardown ()
  (with-temp-buffer
    (let ((other (lambda () 'other)))
      (setq-local completion-at-point-functions (list other 'eglot-completion-at-point))
      (cl-letf (((symbol-function 'heroiclands-eglot--content-buffer-p)
                 (lambda () t))
                ((symbol-function 'eglot-managed-p) (lambda () t)))
        (heroiclands-eglot--manage-capf)
        (should (memq other completion-at-point-functions))
        (should (memq 'heroiclands-eglot-capf completion-at-point-functions))
        (should-not (memq 'eglot-completion-at-point completion-at-point-functions))
        (heroiclands-eglot--teardown-capf)
        (should (memq other completion-at-point-functions))
        (should-not (memq 'heroiclands-eglot-capf completion-at-point-functions))
        (should (memq 'eglot-completion-at-point completion-at-point-functions))))))

(ert-deftest heroiclands-eglot-capf-stays-quiet-in-settled-links ()
  (with-temp-buffer
    (insert "[[being-orca]]")
    (goto-char (+ (point-min) 5))
    (let ((requests 0))
      (cl-letf (((symbol-function 'heroiclands-eglot--content-buffer-p)
                 (lambda () t))
                ((symbol-function 'eglot-managed-p) (lambda () t))
                ((symbol-function 'eglot-completion-at-point)
                 (lambda () (cl-incf requests))))
        (should-not (heroiclands-eglot-capf))
        (should (= requests 0))))))

;;; heroiclands-eglot-test.el ends here
